server:
    port: 8600

spring: 
    application:
        name: apigateway-service
eureka:
    client:
        serviceUrl:
            defaultZone: http://16.187.145.11:8500/eureka/

zuul:
  routes:
    role-service:
      path: /api/roles/**
      #stripPrefix: false
    account-service:
      path: /api/accounts/**
      #stripPrefix: false
    organization-service:
      path: /api/organization/**
      #stripPrefix: false