server:
    port: 8600

spring: 
    application:
        name: apigateway-service
eureka:
    client:
        serviceUrl:
            defaultZone: http://16.187.145.11:8500/eureka/

zuul:
  routes:
    role-service:
      path: /roles/**
      url: forward:/roles
    account-service:
      path: /accounts/**
      url: forward:/accounts
    organization-service:
      path: /organization/**
      url: forward:/organizations