server:
    port: 8600

spring: 
    application:
        name: apigateway-service
eureka:
    client:
        serviceUrl:
            defaultZone: http://16.187.145.11:8500/eureka/

zuul:
  routes:
    role-service:
      path: /roles/**
      stripPrefix: false
    account-service:
      path: /api/accounts/**
      stripPrefix: true
    organization-service:
      path: /organization/**
      stripPrefix: false