server:
    port: 8600
    #全局路径前缀
    contextPath: /api
spring: 
    application:
        name: apigateway-service
eureka:
    client:
        serviceUrl:
            defaultZone: http://16.187.145.11:8500/eureka/

zuul:
  #服务跳转映射，依赖于Eureka的Service-ID
  routes:
    role-service:
      path: /roles/**
      stripPrefix: false
    account-service:
      path: /accounts/**
      stripPrefix: false
    organization-service:
      path: /organizations/**
      stripPrefix: false
    product-service:
      path: /products/**
      stripPrefix: false